spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/sb_demo
    username: postgres
    password: root
#  flyway:
#    url: jdbc:postgresql://localhost:5432/sb_demo
#    user: postgres
#    password: root
#    baseline-on-migrate: true